### ISSUE TITLE
Firefox Branch Capability

### ISSUE THREAD

**Issue by covert8** [abiyani/automate-save-page-as#10]
First and foremost, Thank you for writing this program. It saved my bacon when i needed to save about 250 pages and I can't thank you enough.

Secondly I use Firefox developer branch and the program didn't want to use it. It's an easy fix as i just linked firefox-developer to Firefox and noticed no issues. Personally i'd like to see this fixed from inside the program as it is more elegant.

ps: firefox branches: firefox-developer,firefox-beta,firefox-nightly,(deprecated firefox-aurora).
pps:I'm in the middle of my exams right now and don't have the time to fix it, but if there's no-one else I definitely will.

**Comment by abiyani** [comment]
I am glad that it helped you!

Regarding the feature request - the browser executable path is actually configurable (`--browser`), but it's still restricted to chrome/firefox only (https://github.com/abiyani/automate-save-page-as/blob/master/save_page_as#L112). The reason for that is that we need the title for "Save as" dialog box (which differ across browsers), so I just whitelisted two browsers initially (and hard coded their "save as" dialog box titles). For your own purpose, you can add "firefox-developer", etc in that list to allow them as well (do remember to update line 156 as well if you change it). However I don't want to check in another one-off hacky fix to the repo (it's clearly not scalable to keep on adding browser executables to the list). I don't have free time right now, but if & when I get that, I will refactor code a bit and make it more extensible (like specifying arbitrary browser, and provide the "Save as" dialog box title, etc). But no timeline for it yet.
