### ISSUE TITLE
problem on Debian 9 stretch

### ISSUE THREAD

**Issue by Threepwood77** [abiyani/automate-save-page-as#13]
Hello,
Thanks for the script :)
I use Debian 9 stretch, I have installed xdotools.
Whether with firefox or chrome, the page opens, but there are no catches.
In logs, I have this:

Aug  8 09:19:21 xxxxxxxxxxxxxxx kerrnel: [ 1258.634385] xdotool[1922]: segfault at 20 ip 00007face0fcb346 sp 00007ffd3d6ac490 error 4 in libxdo.so.3[7face0fc4000+b000]
Aug  8 09:25:08 xxxxxxxxxxxxxxxxxxxx kernel: [ 1605.317681] xdotool[2194]: segfault at 20 ip 00007f3cc379f346 sp 00007ffdbb266c20 error 4 in libxdo.so.3[7f3cc3798000+b000]
Aug  8 09:26:28 xxxxxxxxxxxxxxxxxx kernel: [ 1684.747747] xdotool[2323]: segfault at 20 ip 00007f1acba36346 sp 00007ffe012508c0 error 4 in libxdo.so.3[7f1acba2f000+b000]

Do you have any idea of ​​the problem ?

thank you

**Comment by abiyani** [comment]
Sorry for the delayed reply. This error seems to be a segfault in `xdotool` itself (this is a third party software the script internally uses). You can try asking on their mailing list (project page with mailing list link: http://www.semicomplete.com/projects/xdotool).

This tool (`automate-save-page-as`) was written in a time before Chrome supported headless mode. However Google Chrome recently started supporting it natively (yay!). I would strongly suggest that you take a look at this new feature, as it may suffice for your use-case without requiring any additional tools. See: https://developers.google.com/web/updates/2017/04/headless-chrome
