### ISSUE TITLE
Feature request: support for headless use?

### ISSUE THREAD

**Issue by dhowe** [abiyani/automate-save-page-as#14]

**Comment by abiyani** [comment]
What does this feature request mean ? Do you mean using headless chrome in the tool ?

**Comment by dhowe** [comment]
Yes, if possible (or any headless browser really), so that we might use it without a windowing session

**Comment by abiyani** [comment]
If you are using headless mode, then you don't really need this tool (you can already automate saving the page, etc). This tool is specifically meant for X-window session and relies on `xdotool` to send specific key stroke to Browser window.

PS: This tool actually predates headless chrome - if that existed, then I probably wouldn't have wrote this.
