### ISSUE TITLE
Error: Can't open display: (null)

### ISSUE THREAD

**Issue by Richies97** [abiyani/automate-save-page-as#15]
When i start the script i get then Error messages

`
Error: Can't open display: (null)
Failed creating new xdo instance
`

I am running it with firefox on Ubunut 14.04

**Comment by abiyani** [comment]
Are you running it from a non-interactive session ? Try running simply `xdotool` - does that work for you ? My guess would be you are running script in such a way that it can't connect to X server.

**Comment by Richies97** [comment]
Yeah i think that was the problem, I could fix it the solution was adding this to the file

`
export DISPLAY=":0" 
`
`
export XAUTHORITY=/home/grk1lk02/.Xauthority
`
