### ISSUE TITLE
Is there a way to specify a cookie file to use SavePageAs on a site previously logged into?

### ISSUE THREAD

**Issue by bhuether** [abiyani/automate-save-page-as#26]
I am using curl to login and then after login I am trying to save page. Since I can't get wget to replicate FireFox Save As Website Complete, I am hoping to use this Save Page As script.

thanks!

Brian

**Comment by abiyani** [comment]
The tool will open your browser and all your existing cookies in browsers would apply as normal. So say if you are logged into a website in firefox, you would be logged into it when firefox opens thru this tools as well.
