### ISSUE TITLE
Feature request: Close current tab after saving pages

### ISSUE THREAD

**Issue by stucka** [abiyani/automate-save-page-as#5]
Might be helpful when used in scripting scrapes. I suspect Firefox will not hold the 250 pages I'm trying to scrape. =)

**Comment by abiyani** [comment]
It should be already doing it: https://github.com/abiyani/automate-save-page-as/blob/master/save_page_as#L221. Does it not work for you ?

**Comment by stucka** [comment]
It wasn't working with Firefox on Xubuntu 14.04. I don't know what might be
the problem, if it's the window manager or the browser. I can install a
Chromeish browser and try if you'd like.

**Comment by abiyani** [comment]
You don't need to switch your browser. Your desktop environment may have a different key-sequence for closing the tab.

As you can see from the code, the script tries to close the tab by "pressing" Ctrl+F4 (Ctrl+w if the environment is `kde`). So just Change that value to your environment specific key sequence.
