### ISSUE TITLE
Cannot save page when computer is locked

### ISSUE THREAD

**Issue by reyy** [abiyani/automate-save-page-as#6]
The script is working perfectly fine (Opens FF, Saves, Closes FF) when I run it manually on terminal but I need it to run without human intervention, so I set a cron job to save the page everyday.

Unfortunately when the computer is locked, the script only opens the page on FF and does not save or close it. Im not sure if its an Ubuntu problem or a script problem (perhaps the keyboard shortcuts dont work when the computer is not logged in?), but I just wanted to check if anybody else has encountered and has a workaround.

Oh and I'm running Ubuntu 14.04LTS / Firefox. Thanks!

**Comment by abiyani** [comment]
@reyy: Thanks for opening the issue. I think the most plausible cause (as you mentioned) is that "pressing" any key when screen is locked brings up the login screen (as expected), which makes it impossible for the script to function further. I am currently traveling, so won't have the bandwidth to reproduce/try-to-fix the problem for at least a few weeks -- I think it will most likely fall in the category of "Won't fix" anyway (as there is not much the script itself can do about it).

Two possibilities (untested) which come to mind (both of them are pretty **UGLY** from security perspective -- use your own judgement about risk tradeoffs in your particular scenario):
 - You can try removing the password requirement when unlocking screen.
 - You can modify the script to enter your password in the login prompt as the first thing (however, this will require you to hardcode your password in the script - maybe create a dummy user account).
