### ISSUE TITLE
sync flag did not work

### ISSUE THREAD

**Issue by normukhamedov** [abiyani/automate-save-page-as#7]
what is that sync option here 
browser_wid="$(xdotool search --sync --onlyvisible --class "${browser}" | head -n 1)"?
it just never worked with that option. Is it important? Please explain.

thanks for the nice tool.

**Comment by abiyani** [comment]
This is most likely because you are using an outdated version of the xdotool. You can either upgrade it, or try removing `--sync` (it's not essential to script's functioning).
