### ISSUE TITLE
when i do ctrl+S to overwrite existing file - it fails....

### ISSUE THREAD

**Issue by normukhamedov** [abiyani/automate-save-page-as#8]
when i do ctrl+S to overwrite existing file - it fails....

thanks

**Comment by abiyani** [comment]
This is the expected behavior. Please use a unique name for the file, or just remove the file before running the script.

**Comment by normukhamedov** [comment]
thanks abiyani, love your script ....I was wondering if you can add the option to save html page as complete page and/or html only. (sometimes switching between the two is required)   thanks
