### ISSUE TITLE
i wonder if you could help with "Tab" key

### ISSUE THREAD

**Issue by normukhamedov** [abiyani/automate-save-page-as#9]
when i send several Tab keys after page is loaded - it works ok. But my enter key does not work....
Anything i am missing? thanks

**Comment by abiyani** [comment]
I am not sure what do you mean by sending "Tab key" ? The script is completely automated (you don't need to press any key after running it), but you won't really be able to use your computer (at least the same X windows session) for anything else while it's running.

**Comment by normukhamedov** [comment]
When script loads the  page I send tab Key within the script everything is automatic no manual interactions . But  enter key doesn't work after that. This only case with Chrome browser and not Firefox. Thanks


Sent via the Samsung GALAXY S®4, an AT&T 4G LTE smartphone

-------- Original message --------

**Comment by normukhamedov** [comment]
Hi Abiyani,
basically "xdotool key Tab Tab Tab Return"    works with Firefox but not with chrome. 
Tabs work fine for both but Return works only in Firefox.
 Is there a different way in chrome to send Return command in chrome.....?
Could you please try this yourself? 
 that would be highly appreciated.....
Thanks

**Comment by abiyani** [comment]
The script doesn't use "Tab" key anywhere. If it is an xdotool specific question, you can try asking on their mailing list. My hunch is that `Return` is probably not what you expect, and you instead need `KP_Enter` or something else (https://groups.google.com/forum/#!topic/xdotool-users/oV40iJbLfJ8).
